### ISSUE TITLE
CONDA_PREFIX changes due to --use-conda

### ISSUE THREAD

**Issue by zhaoc1** [sunbeam-labs/sbx_metaphlan#2]
Hi Jesse,

Since chop doesn't have network access to bitbucket, we need to walk around the metaphlan bowtie2 db installing. Instead of `metaphlan2.py --install`, I am trying to keep a local of the mpa20_v20 database, and copy the files to $CONDA_PREFIX. However, since we also use --use-conda for metaphaln2, the $CONDA_PREFIX no longer points to the `sunbeam` environment. 

Is there a good way to walk around this issue? Or shall I just install metaphlan from source into $CONDA_FP/opt ?

Any suggestions? 

Thanks!

Chunyu

**Comment by ressy** [comment]
Maybe instead of putting the database where metaphlan expects it by default, we should put it elsewhere and use `metaphlan2.py --bowtie2db $DB` / `bowtie2 -x $DB` and point to it directly.  But then, that still leaves the question of the best way to detect the containing environment... I'll think on this and get back to you.

**Comment by ressy** [comment]
Since that special environment is loaded just within specific rules, I think we can detect the original Sunbeam environment before the special one is loaded, and then use that stored path inside the rule.  I'll give that a try.  We could also (independently of any of that) support a config option for the database location, too.

**Comment by ressy** [comment]
All set.  This now stores the default DB in `$CONDA_PREFIX/opt/metaphlan_databases`.   #3 will be for making the DB itself customizable.
